{
 "title": "Logística",
 "time": { "from": "2026-04-26T22:35:54.338Z", "to": "2026-04-26T22:52:40.778Z" },
 "panels": [
  {
   "title": "Total despachado",
   "type": "stat",
   "gridPos": { "h": 9, "w": 5, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"ace\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"logistica\")\r\n  |> filter(fn: (r) => r._field == \"quantidade\")\r\n  |> sum()"
    }
   ]
  },
  {
   "title": "Por tipo (veículo x peça)",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 10, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"ace\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"logistica\")\r\n  |> pivot(rowKey:[\"_time\"], columnKey:[\"_field\"], valueColumn:\"_value\")\r\n  |> group(columns: [\"tipo\"])\r\n  |> sum(column: \"quantidade\")"
    }
   ]
  },
  {
   "title": "Destino",
   "type": "bargauge",
   "gridPos": { "h": 11, "w": 16, "x": 4, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"ace\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"logistica\")\r\n  |> pivot(rowKey:[\"_time\"], columnKey:[\"_field\"], valueColumn:\"_value\")\r\n  |> group(columns: [\"destino\"])\r\n  |> sum(column: \"quantidade\")"
    }
   ]
  },
  {
   "title": "Envios por minuto",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 16, "x": 4, "y": 20 },
   "targets": [
    {
     "query": "from(bucket: \"ace\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"logistica\")\r\n  |> filter(fn: (r) => r._field == \"quantidade\")\r\n  |> aggregateWindow(every: 1m, fn: sum, createEmpty: false)"
    }
   ]
  }
 ]
}