{
 "title": "Produção",
 "time": { "from": "now-12h", "to": "now" },
 "panels": [
  {
   "title": "KPI - Key Performance Indicator (Indicador-Chave de Desempenho)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "Veículos Produzidos",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"ace\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"producao\")\r\n  |> pivot(rowKey:[\"_time\"], columnKey:[\"_field\"], valueColumn:\"_value\")\r\n  |> keep(columns: [\"chassi\"])\r\n  |> distinct(column: \"chassi\")\r\n  |> count()"
    }
   ]
  },
  {
   "title": "Mensagens processadas",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"ace\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"producao\")\r\n  |> filter(fn: (r) => r._field == \"quantidade\")\r\n  |> sum()"
    }
   ]
  },
  { "title": "Inconsistências", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Eventos por Etapa",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 14, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"ace\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"producao\")\r\n  |> pivot(rowKey:[\"_time\"], columnKey:[\"_field\"], valueColumn:\"_value\")\r\n  |> group(columns: [\"etapa\"])\r\n  |> sum(column: \"quantidade\")"
    }
   ]
  },
  {
   "title": "Status por Etapa",
   "type": "table",
   "gridPos": { "h": 9, "w": 10, "x": 14, "y": 10 },
   "targets": [
    {
     "query": "from(bucket: \"ace\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"producao\")\r\n  |> pivot(rowKey:[\"_time\"], columnKey:[\"_field\"], valueColumn:\"_value\")\r\n  |> group(columns: [\"etapa\", \"status\"])\r\n  |> sum(column: \"quantidade\")\r\n  |> group()\r\n  |> pivot(\r\n      rowKey: [\"etapa\"],\r\n      columnKey: [\"status\"],\r\n      valueColumn: \"quantidade\"\r\n  )"
    }
   ]
  }
 ]
}